name: make poster.pdf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: sudo apt install texlive-pictures texlive-latex-extra texlive-fonts-extra

    - name: Build
      run: make

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: joss-poster-pdf
        path: joss-poster.pdf
